/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.dair.sgdb.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-10-18")
public class TravelCommand implements org.apache.thrift.TBase<TravelCommand, TravelCommand._Fields>, java.io.Serializable, Cloneable, Comparable<TravelCommand> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TravelCommand");

  private static final org.apache.thrift.protocol.TField TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("type", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField TRAVEL_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("travelId", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField STEP_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("stepId", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField REPLY_TO_FIELD_DESC = new org.apache.thrift.protocol.TField("reply_to", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField GET_FROM_FIELD_DESC = new org.apache.thrift.protocol.TField("get_from", org.apache.thrift.protocol.TType.I32, (short)5);
  private static final org.apache.thrift.protocol.TField PAYLOAD_FIELD_DESC = new org.apache.thrift.protocol.TField("payload", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField TS_FIELD_DESC = new org.apache.thrift.protocol.TField("ts", org.apache.thrift.protocol.TType.I64, (short)7);
  private static final org.apache.thrift.protocol.TField EXT_SRV_FIELD_DESC = new org.apache.thrift.protocol.TField("ext_srv", org.apache.thrift.protocol.TType.LIST, (short)8);
  private static final org.apache.thrift.protocol.TField VALS_FIELD_DESC = new org.apache.thrift.protocol.TField("vals", org.apache.thrift.protocol.TType.LIST, (short)9);
  private static final org.apache.thrift.protocol.TField KEYS_FIELD_DESC = new org.apache.thrift.protocol.TField("keys", org.apache.thrift.protocol.TType.LIST, (short)10);
  private static final org.apache.thrift.protocol.TField SUB_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("sub_type", org.apache.thrift.protocol.TType.I32, (short)11);
  private static final org.apache.thrift.protocol.TField LOCAL_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("local_id", org.apache.thrift.protocol.TType.I32, (short)12);
  private static final org.apache.thrift.protocol.TField EPOCH_FIELD_DESC = new org.apache.thrift.protocol.TField("epoch", org.apache.thrift.protocol.TType.LIST, (short)13);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TravelCommandStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TravelCommandTupleSchemeFactory();

  /**
   * 
   * @see TravelCommandType
   */
  public TravelCommandType type; // required
  public long travelId; // required
  public int stepId; // required
  public int reply_to; // optional
  public int get_from; // optional
  public java.lang.String payload; // optional
  public long ts; // optional
  public java.util.List<java.lang.Integer> ext_srv; // optional
  public java.util.List<KeyValue> vals; // optional
  public java.util.List<java.nio.ByteBuffer> keys; // optional
  public int sub_type; // optional
  public int local_id; // optional
  public java.util.List<EpochEntity> epoch; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see TravelCommandType
     */
    TYPE((short)1, "type"),
    TRAVEL_ID((short)2, "travelId"),
    STEP_ID((short)3, "stepId"),
    REPLY_TO((short)4, "reply_to"),
    GET_FROM((short)5, "get_from"),
    PAYLOAD((short)6, "payload"),
    TS((short)7, "ts"),
    EXT_SRV((short)8, "ext_srv"),
    VALS((short)9, "vals"),
    KEYS((short)10, "keys"),
    SUB_TYPE((short)11, "sub_type"),
    LOCAL_ID((short)12, "local_id"),
    EPOCH((short)13, "epoch");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TYPE
          return TYPE;
        case 2: // TRAVEL_ID
          return TRAVEL_ID;
        case 3: // STEP_ID
          return STEP_ID;
        case 4: // REPLY_TO
          return REPLY_TO;
        case 5: // GET_FROM
          return GET_FROM;
        case 6: // PAYLOAD
          return PAYLOAD;
        case 7: // TS
          return TS;
        case 8: // EXT_SRV
          return EXT_SRV;
        case 9: // VALS
          return VALS;
        case 10: // KEYS
          return KEYS;
        case 11: // SUB_TYPE
          return SUB_TYPE;
        case 12: // LOCAL_ID
          return LOCAL_ID;
        case 13: // EPOCH
          return EPOCH;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TRAVELID_ISSET_ID = 0;
  private static final int __STEPID_ISSET_ID = 1;
  private static final int __REPLY_TO_ISSET_ID = 2;
  private static final int __GET_FROM_ISSET_ID = 3;
  private static final int __TS_ISSET_ID = 4;
  private static final int __SUB_TYPE_ISSET_ID = 5;
  private static final int __LOCAL_ID_ISSET_ID = 6;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.REPLY_TO,_Fields.GET_FROM,_Fields.PAYLOAD,_Fields.TS,_Fields.EXT_SRV,_Fields.VALS,_Fields.KEYS,_Fields.SUB_TYPE,_Fields.LOCAL_ID,_Fields.EPOCH};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TYPE, new org.apache.thrift.meta_data.FieldMetaData("type", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, TravelCommandType.class)));
    tmpMap.put(_Fields.TRAVEL_ID, new org.apache.thrift.meta_data.FieldMetaData("travelId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.STEP_ID, new org.apache.thrift.meta_data.FieldMetaData("stepId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.REPLY_TO, new org.apache.thrift.meta_data.FieldMetaData("reply_to", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.GET_FROM, new org.apache.thrift.meta_data.FieldMetaData("get_from", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.PAYLOAD, new org.apache.thrift.meta_data.FieldMetaData("payload", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TS, new org.apache.thrift.meta_data.FieldMetaData("ts", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.EXT_SRV, new org.apache.thrift.meta_data.FieldMetaData("ext_srv", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32))));
    tmpMap.put(_Fields.VALS, new org.apache.thrift.meta_data.FieldMetaData("vals", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, KeyValue.class))));
    tmpMap.put(_Fields.KEYS, new org.apache.thrift.meta_data.FieldMetaData("keys", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING            , true))));
    tmpMap.put(_Fields.SUB_TYPE, new org.apache.thrift.meta_data.FieldMetaData("sub_type", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.LOCAL_ID, new org.apache.thrift.meta_data.FieldMetaData("local_id", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.EPOCH, new org.apache.thrift.meta_data.FieldMetaData("epoch", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, EpochEntity.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TravelCommand.class, metaDataMap);
  }

  public TravelCommand() {
  }

  public TravelCommand(
    TravelCommandType type,
    long travelId,
    int stepId)
  {
    this();
    this.type = type;
    this.travelId = travelId;
    setTravelIdIsSet(true);
    this.stepId = stepId;
    setStepIdIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TravelCommand(TravelCommand other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetType()) {
      this.type = other.type;
    }
    this.travelId = other.travelId;
    this.stepId = other.stepId;
    this.reply_to = other.reply_to;
    this.get_from = other.get_from;
    if (other.isSetPayload()) {
      this.payload = other.payload;
    }
    this.ts = other.ts;
    if (other.isSetExt_srv()) {
      java.util.List<java.lang.Integer> __this__ext_srv = new java.util.ArrayList<java.lang.Integer>(other.ext_srv);
      this.ext_srv = __this__ext_srv;
    }
    if (other.isSetVals()) {
      java.util.List<KeyValue> __this__vals = new java.util.ArrayList<KeyValue>(other.vals.size());
      for (KeyValue other_element : other.vals) {
        __this__vals.add(new KeyValue(other_element));
      }
      this.vals = __this__vals;
    }
    if (other.isSetKeys()) {
      java.util.List<java.nio.ByteBuffer> __this__keys = new java.util.ArrayList<java.nio.ByteBuffer>(other.keys);
      this.keys = __this__keys;
    }
    this.sub_type = other.sub_type;
    this.local_id = other.local_id;
    if (other.isSetEpoch()) {
      java.util.List<EpochEntity> __this__epoch = new java.util.ArrayList<EpochEntity>(other.epoch.size());
      for (EpochEntity other_element : other.epoch) {
        __this__epoch.add(new EpochEntity(other_element));
      }
      this.epoch = __this__epoch;
    }
  }

  public TravelCommand deepCopy() {
    return new TravelCommand(this);
  }

  @Override
  public void clear() {
    this.type = null;
    setTravelIdIsSet(false);
    this.travelId = 0;
    setStepIdIsSet(false);
    this.stepId = 0;
    setReply_toIsSet(false);
    this.reply_to = 0;
    setGet_fromIsSet(false);
    this.get_from = 0;
    this.payload = null;
    setTsIsSet(false);
    this.ts = 0;
    this.ext_srv = null;
    this.vals = null;
    this.keys = null;
    setSub_typeIsSet(false);
    this.sub_type = 0;
    setLocal_idIsSet(false);
    this.local_id = 0;
    this.epoch = null;
  }

  /**
   * 
   * @see TravelCommandType
   */
  public TravelCommandType getType() {
    return this.type;
  }

  /**
   * 
   * @see TravelCommandType
   */
  public TravelCommand setType(TravelCommandType type) {
    this.type = type;
    return this;
  }

  public void unsetType() {
    this.type = null;
  }

  /** Returns true if field type is set (has been assigned a value) and false otherwise */
  public boolean isSetType() {
    return this.type != null;
  }

  public void setTypeIsSet(boolean value) {
    if (!value) {
      this.type = null;
    }
  }

  public long getTravelId() {
    return this.travelId;
  }

  public TravelCommand setTravelId(long travelId) {
    this.travelId = travelId;
    setTravelIdIsSet(true);
    return this;
  }

  public void unsetTravelId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TRAVELID_ISSET_ID);
  }

  /** Returns true if field travelId is set (has been assigned a value) and false otherwise */
  public boolean isSetTravelId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TRAVELID_ISSET_ID);
  }

  public void setTravelIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TRAVELID_ISSET_ID, value);
  }

  public int getStepId() {
    return this.stepId;
  }

  public TravelCommand setStepId(int stepId) {
    this.stepId = stepId;
    setStepIdIsSet(true);
    return this;
  }

  public void unsetStepId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __STEPID_ISSET_ID);
  }

  /** Returns true if field stepId is set (has been assigned a value) and false otherwise */
  public boolean isSetStepId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __STEPID_ISSET_ID);
  }

  public void setStepIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __STEPID_ISSET_ID, value);
  }

  public int getReply_to() {
    return this.reply_to;
  }

  public TravelCommand setReply_to(int reply_to) {
    this.reply_to = reply_to;
    setReply_toIsSet(true);
    return this;
  }

  public void unsetReply_to() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __REPLY_TO_ISSET_ID);
  }

  /** Returns true if field reply_to is set (has been assigned a value) and false otherwise */
  public boolean isSetReply_to() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __REPLY_TO_ISSET_ID);
  }

  public void setReply_toIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __REPLY_TO_ISSET_ID, value);
  }

  public int getGet_from() {
    return this.get_from;
  }

  public TravelCommand setGet_from(int get_from) {
    this.get_from = get_from;
    setGet_fromIsSet(true);
    return this;
  }

  public void unsetGet_from() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __GET_FROM_ISSET_ID);
  }

  /** Returns true if field get_from is set (has been assigned a value) and false otherwise */
  public boolean isSetGet_from() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __GET_FROM_ISSET_ID);
  }

  public void setGet_fromIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __GET_FROM_ISSET_ID, value);
  }

  public java.lang.String getPayload() {
    return this.payload;
  }

  public TravelCommand setPayload(java.lang.String payload) {
    this.payload = payload;
    return this;
  }

  public void unsetPayload() {
    this.payload = null;
  }

  /** Returns true if field payload is set (has been assigned a value) and false otherwise */
  public boolean isSetPayload() {
    return this.payload != null;
  }

  public void setPayloadIsSet(boolean value) {
    if (!value) {
      this.payload = null;
    }
  }

  public long getTs() {
    return this.ts;
  }

  public TravelCommand setTs(long ts) {
    this.ts = ts;
    setTsIsSet(true);
    return this;
  }

  public void unsetTs() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TS_ISSET_ID);
  }

  /** Returns true if field ts is set (has been assigned a value) and false otherwise */
  public boolean isSetTs() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TS_ISSET_ID);
  }

  public void setTsIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TS_ISSET_ID, value);
  }

  public int getExt_srvSize() {
    return (this.ext_srv == null) ? 0 : this.ext_srv.size();
  }

  public java.util.Iterator<java.lang.Integer> getExt_srvIterator() {
    return (this.ext_srv == null) ? null : this.ext_srv.iterator();
  }

  public void addToExt_srv(int elem) {
    if (this.ext_srv == null) {
      this.ext_srv = new java.util.ArrayList<java.lang.Integer>();
    }
    this.ext_srv.add(elem);
  }

  public java.util.List<java.lang.Integer> getExt_srv() {
    return this.ext_srv;
  }

  public TravelCommand setExt_srv(java.util.List<java.lang.Integer> ext_srv) {
    this.ext_srv = ext_srv;
    return this;
  }

  public void unsetExt_srv() {
    this.ext_srv = null;
  }

  /** Returns true if field ext_srv is set (has been assigned a value) and false otherwise */
  public boolean isSetExt_srv() {
    return this.ext_srv != null;
  }

  public void setExt_srvIsSet(boolean value) {
    if (!value) {
      this.ext_srv = null;
    }
  }

  public int getValsSize() {
    return (this.vals == null) ? 0 : this.vals.size();
  }

  public java.util.Iterator<KeyValue> getValsIterator() {
    return (this.vals == null) ? null : this.vals.iterator();
  }

  public void addToVals(KeyValue elem) {
    if (this.vals == null) {
      this.vals = new java.util.ArrayList<KeyValue>();
    }
    this.vals.add(elem);
  }

  public java.util.List<KeyValue> getVals() {
    return this.vals;
  }

  public TravelCommand setVals(java.util.List<KeyValue> vals) {
    this.vals = vals;
    return this;
  }

  public void unsetVals() {
    this.vals = null;
  }

  /** Returns true if field vals is set (has been assigned a value) and false otherwise */
  public boolean isSetVals() {
    return this.vals != null;
  }

  public void setValsIsSet(boolean value) {
    if (!value) {
      this.vals = null;
    }
  }

  public int getKeysSize() {
    return (this.keys == null) ? 0 : this.keys.size();
  }

  public java.util.Iterator<java.nio.ByteBuffer> getKeysIterator() {
    return (this.keys == null) ? null : this.keys.iterator();
  }

  public void addToKeys(java.nio.ByteBuffer elem) {
    if (this.keys == null) {
      this.keys = new java.util.ArrayList<java.nio.ByteBuffer>();
    }
    this.keys.add(elem);
  }

  public java.util.List<java.nio.ByteBuffer> getKeys() {
    return this.keys;
  }

  public TravelCommand setKeys(java.util.List<java.nio.ByteBuffer> keys) {
    this.keys = keys;
    return this;
  }

  public void unsetKeys() {
    this.keys = null;
  }

  /** Returns true if field keys is set (has been assigned a value) and false otherwise */
  public boolean isSetKeys() {
    return this.keys != null;
  }

  public void setKeysIsSet(boolean value) {
    if (!value) {
      this.keys = null;
    }
  }

  public int getSub_type() {
    return this.sub_type;
  }

  public TravelCommand setSub_type(int sub_type) {
    this.sub_type = sub_type;
    setSub_typeIsSet(true);
    return this;
  }

  public void unsetSub_type() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SUB_TYPE_ISSET_ID);
  }

  /** Returns true if field sub_type is set (has been assigned a value) and false otherwise */
  public boolean isSetSub_type() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SUB_TYPE_ISSET_ID);
  }

  public void setSub_typeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SUB_TYPE_ISSET_ID, value);
  }

  public int getLocal_id() {
    return this.local_id;
  }

  public TravelCommand setLocal_id(int local_id) {
    this.local_id = local_id;
    setLocal_idIsSet(true);
    return this;
  }

  public void unsetLocal_id() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LOCAL_ID_ISSET_ID);
  }

  /** Returns true if field local_id is set (has been assigned a value) and false otherwise */
  public boolean isSetLocal_id() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LOCAL_ID_ISSET_ID);
  }

  public void setLocal_idIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LOCAL_ID_ISSET_ID, value);
  }

  public int getEpochSize() {
    return (this.epoch == null) ? 0 : this.epoch.size();
  }

  public java.util.Iterator<EpochEntity> getEpochIterator() {
    return (this.epoch == null) ? null : this.epoch.iterator();
  }

  public void addToEpoch(EpochEntity elem) {
    if (this.epoch == null) {
      this.epoch = new java.util.ArrayList<EpochEntity>();
    }
    this.epoch.add(elem);
  }

  public java.util.List<EpochEntity> getEpoch() {
    return this.epoch;
  }

  public TravelCommand setEpoch(java.util.List<EpochEntity> epoch) {
    this.epoch = epoch;
    return this;
  }

  public void unsetEpoch() {
    this.epoch = null;
  }

  /** Returns true if field epoch is set (has been assigned a value) and false otherwise */
  public boolean isSetEpoch() {
    return this.epoch != null;
  }

  public void setEpochIsSet(boolean value) {
    if (!value) {
      this.epoch = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case TYPE:
      if (value == null) {
        unsetType();
      } else {
        setType((TravelCommandType)value);
      }
      break;

    case TRAVEL_ID:
      if (value == null) {
        unsetTravelId();
      } else {
        setTravelId((java.lang.Long)value);
      }
      break;

    case STEP_ID:
      if (value == null) {
        unsetStepId();
      } else {
        setStepId((java.lang.Integer)value);
      }
      break;

    case REPLY_TO:
      if (value == null) {
        unsetReply_to();
      } else {
        setReply_to((java.lang.Integer)value);
      }
      break;

    case GET_FROM:
      if (value == null) {
        unsetGet_from();
      } else {
        setGet_from((java.lang.Integer)value);
      }
      break;

    case PAYLOAD:
      if (value == null) {
        unsetPayload();
      } else {
        setPayload((java.lang.String)value);
      }
      break;

    case TS:
      if (value == null) {
        unsetTs();
      } else {
        setTs((java.lang.Long)value);
      }
      break;

    case EXT_SRV:
      if (value == null) {
        unsetExt_srv();
      } else {
        setExt_srv((java.util.List<java.lang.Integer>)value);
      }
      break;

    case VALS:
      if (value == null) {
        unsetVals();
      } else {
        setVals((java.util.List<KeyValue>)value);
      }
      break;

    case KEYS:
      if (value == null) {
        unsetKeys();
      } else {
        setKeys((java.util.List<java.nio.ByteBuffer>)value);
      }
      break;

    case SUB_TYPE:
      if (value == null) {
        unsetSub_type();
      } else {
        setSub_type((java.lang.Integer)value);
      }
      break;

    case LOCAL_ID:
      if (value == null) {
        unsetLocal_id();
      } else {
        setLocal_id((java.lang.Integer)value);
      }
      break;

    case EPOCH:
      if (value == null) {
        unsetEpoch();
      } else {
        setEpoch((java.util.List<EpochEntity>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case TYPE:
      return getType();

    case TRAVEL_ID:
      return getTravelId();

    case STEP_ID:
      return getStepId();

    case REPLY_TO:
      return getReply_to();

    case GET_FROM:
      return getGet_from();

    case PAYLOAD:
      return getPayload();

    case TS:
      return getTs();

    case EXT_SRV:
      return getExt_srv();

    case VALS:
      return getVals();

    case KEYS:
      return getKeys();

    case SUB_TYPE:
      return getSub_type();

    case LOCAL_ID:
      return getLocal_id();

    case EPOCH:
      return getEpoch();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case TYPE:
      return isSetType();
    case TRAVEL_ID:
      return isSetTravelId();
    case STEP_ID:
      return isSetStepId();
    case REPLY_TO:
      return isSetReply_to();
    case GET_FROM:
      return isSetGet_from();
    case PAYLOAD:
      return isSetPayload();
    case TS:
      return isSetTs();
    case EXT_SRV:
      return isSetExt_srv();
    case VALS:
      return isSetVals();
    case KEYS:
      return isSetKeys();
    case SUB_TYPE:
      return isSetSub_type();
    case LOCAL_ID:
      return isSetLocal_id();
    case EPOCH:
      return isSetEpoch();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TravelCommand)
      return this.equals((TravelCommand)that);
    return false;
  }

  public boolean equals(TravelCommand that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_type = true && this.isSetType();
    boolean that_present_type = true && that.isSetType();
    if (this_present_type || that_present_type) {
      if (!(this_present_type && that_present_type))
        return false;
      if (!this.type.equals(that.type))
        return false;
    }

    boolean this_present_travelId = true;
    boolean that_present_travelId = true;
    if (this_present_travelId || that_present_travelId) {
      if (!(this_present_travelId && that_present_travelId))
        return false;
      if (this.travelId != that.travelId)
        return false;
    }

    boolean this_present_stepId = true;
    boolean that_present_stepId = true;
    if (this_present_stepId || that_present_stepId) {
      if (!(this_present_stepId && that_present_stepId))
        return false;
      if (this.stepId != that.stepId)
        return false;
    }

    boolean this_present_reply_to = true && this.isSetReply_to();
    boolean that_present_reply_to = true && that.isSetReply_to();
    if (this_present_reply_to || that_present_reply_to) {
      if (!(this_present_reply_to && that_present_reply_to))
        return false;
      if (this.reply_to != that.reply_to)
        return false;
    }

    boolean this_present_get_from = true && this.isSetGet_from();
    boolean that_present_get_from = true && that.isSetGet_from();
    if (this_present_get_from || that_present_get_from) {
      if (!(this_present_get_from && that_present_get_from))
        return false;
      if (this.get_from != that.get_from)
        return false;
    }

    boolean this_present_payload = true && this.isSetPayload();
    boolean that_present_payload = true && that.isSetPayload();
    if (this_present_payload || that_present_payload) {
      if (!(this_present_payload && that_present_payload))
        return false;
      if (!this.payload.equals(that.payload))
        return false;
    }

    boolean this_present_ts = true && this.isSetTs();
    boolean that_present_ts = true && that.isSetTs();
    if (this_present_ts || that_present_ts) {
      if (!(this_present_ts && that_present_ts))
        return false;
      if (this.ts != that.ts)
        return false;
    }

    boolean this_present_ext_srv = true && this.isSetExt_srv();
    boolean that_present_ext_srv = true && that.isSetExt_srv();
    if (this_present_ext_srv || that_present_ext_srv) {
      if (!(this_present_ext_srv && that_present_ext_srv))
        return false;
      if (!this.ext_srv.equals(that.ext_srv))
        return false;
    }

    boolean this_present_vals = true && this.isSetVals();
    boolean that_present_vals = true && that.isSetVals();
    if (this_present_vals || that_present_vals) {
      if (!(this_present_vals && that_present_vals))
        return false;
      if (!this.vals.equals(that.vals))
        return false;
    }

    boolean this_present_keys = true && this.isSetKeys();
    boolean that_present_keys = true && that.isSetKeys();
    if (this_present_keys || that_present_keys) {
      if (!(this_present_keys && that_present_keys))
        return false;
      if (!this.keys.equals(that.keys))
        return false;
    }

    boolean this_present_sub_type = true && this.isSetSub_type();
    boolean that_present_sub_type = true && that.isSetSub_type();
    if (this_present_sub_type || that_present_sub_type) {
      if (!(this_present_sub_type && that_present_sub_type))
        return false;
      if (this.sub_type != that.sub_type)
        return false;
    }

    boolean this_present_local_id = true && this.isSetLocal_id();
    boolean that_present_local_id = true && that.isSetLocal_id();
    if (this_present_local_id || that_present_local_id) {
      if (!(this_present_local_id && that_present_local_id))
        return false;
      if (this.local_id != that.local_id)
        return false;
    }

    boolean this_present_epoch = true && this.isSetEpoch();
    boolean that_present_epoch = true && that.isSetEpoch();
    if (this_present_epoch || that_present_epoch) {
      if (!(this_present_epoch && that_present_epoch))
        return false;
      if (!this.epoch.equals(that.epoch))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetType()) ? 131071 : 524287);
    if (isSetType())
      hashCode = hashCode * 8191 + type.getValue();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(travelId);

    hashCode = hashCode * 8191 + stepId;

    hashCode = hashCode * 8191 + ((isSetReply_to()) ? 131071 : 524287);
    if (isSetReply_to())
      hashCode = hashCode * 8191 + reply_to;

    hashCode = hashCode * 8191 + ((isSetGet_from()) ? 131071 : 524287);
    if (isSetGet_from())
      hashCode = hashCode * 8191 + get_from;

    hashCode = hashCode * 8191 + ((isSetPayload()) ? 131071 : 524287);
    if (isSetPayload())
      hashCode = hashCode * 8191 + payload.hashCode();

    hashCode = hashCode * 8191 + ((isSetTs()) ? 131071 : 524287);
    if (isSetTs())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(ts);

    hashCode = hashCode * 8191 + ((isSetExt_srv()) ? 131071 : 524287);
    if (isSetExt_srv())
      hashCode = hashCode * 8191 + ext_srv.hashCode();

    hashCode = hashCode * 8191 + ((isSetVals()) ? 131071 : 524287);
    if (isSetVals())
      hashCode = hashCode * 8191 + vals.hashCode();

    hashCode = hashCode * 8191 + ((isSetKeys()) ? 131071 : 524287);
    if (isSetKeys())
      hashCode = hashCode * 8191 + keys.hashCode();

    hashCode = hashCode * 8191 + ((isSetSub_type()) ? 131071 : 524287);
    if (isSetSub_type())
      hashCode = hashCode * 8191 + sub_type;

    hashCode = hashCode * 8191 + ((isSetLocal_id()) ? 131071 : 524287);
    if (isSetLocal_id())
      hashCode = hashCode * 8191 + local_id;

    hashCode = hashCode * 8191 + ((isSetEpoch()) ? 131071 : 524287);
    if (isSetEpoch())
      hashCode = hashCode * 8191 + epoch.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TravelCommand other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetType()).compareTo(other.isSetType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.type, other.type);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetTravelId()).compareTo(other.isSetTravelId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTravelId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.travelId, other.travelId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetStepId()).compareTo(other.isSetStepId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStepId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.stepId, other.stepId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetReply_to()).compareTo(other.isSetReply_to());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReply_to()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.reply_to, other.reply_to);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetGet_from()).compareTo(other.isSetGet_from());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGet_from()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.get_from, other.get_from);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPayload()).compareTo(other.isSetPayload());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPayload()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.payload, other.payload);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetTs()).compareTo(other.isSetTs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ts, other.ts);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetExt_srv()).compareTo(other.isSetExt_srv());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExt_srv()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ext_srv, other.ext_srv);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetVals()).compareTo(other.isSetVals());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVals()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.vals, other.vals);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetKeys()).compareTo(other.isSetKeys());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetKeys()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.keys, other.keys);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSub_type()).compareTo(other.isSetSub_type());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSub_type()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sub_type, other.sub_type);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetLocal_id()).compareTo(other.isSetLocal_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLocal_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.local_id, other.local_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetEpoch()).compareTo(other.isSetEpoch());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEpoch()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.epoch, other.epoch);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TravelCommand(");
    boolean first = true;

    sb.append("type:");
    if (this.type == null) {
      sb.append("null");
    } else {
      sb.append(this.type);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("travelId:");
    sb.append(this.travelId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("stepId:");
    sb.append(this.stepId);
    first = false;
    if (isSetReply_to()) {
      if (!first) sb.append(", ");
      sb.append("reply_to:");
      sb.append(this.reply_to);
      first = false;
    }
    if (isSetGet_from()) {
      if (!first) sb.append(", ");
      sb.append("get_from:");
      sb.append(this.get_from);
      first = false;
    }
    if (isSetPayload()) {
      if (!first) sb.append(", ");
      sb.append("payload:");
      if (this.payload == null) {
        sb.append("null");
      } else {
        sb.append(this.payload);
      }
      first = false;
    }
    if (isSetTs()) {
      if (!first) sb.append(", ");
      sb.append("ts:");
      sb.append(this.ts);
      first = false;
    }
    if (isSetExt_srv()) {
      if (!first) sb.append(", ");
      sb.append("ext_srv:");
      if (this.ext_srv == null) {
        sb.append("null");
      } else {
        sb.append(this.ext_srv);
      }
      first = false;
    }
    if (isSetVals()) {
      if (!first) sb.append(", ");
      sb.append("vals:");
      if (this.vals == null) {
        sb.append("null");
      } else {
        sb.append(this.vals);
      }
      first = false;
    }
    if (isSetKeys()) {
      if (!first) sb.append(", ");
      sb.append("keys:");
      if (this.keys == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.keys, sb);
      }
      first = false;
    }
    if (isSetSub_type()) {
      if (!first) sb.append(", ");
      sb.append("sub_type:");
      sb.append(this.sub_type);
      first = false;
    }
    if (isSetLocal_id()) {
      if (!first) sb.append(", ");
      sb.append("local_id:");
      sb.append(this.local_id);
      first = false;
    }
    if (isSetEpoch()) {
      if (!first) sb.append(", ");
      sb.append("epoch:");
      if (this.epoch == null) {
        sb.append("null");
      } else {
        sb.append(this.epoch);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (type == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'type' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'travelId' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'stepId' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TravelCommandStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TravelCommandStandardScheme getScheme() {
      return new TravelCommandStandardScheme();
    }
  }

  private static class TravelCommandStandardScheme extends org.apache.thrift.scheme.StandardScheme<TravelCommand> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TravelCommand struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.type = edu.dair.sgdb.thrift.TravelCommandType.findByValue(iprot.readI32());
              struct.setTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TRAVEL_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.travelId = iprot.readI64();
              struct.setTravelIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // STEP_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.stepId = iprot.readI32();
              struct.setStepIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // REPLY_TO
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.reply_to = iprot.readI32();
              struct.setReply_toIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // GET_FROM
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.get_from = iprot.readI32();
              struct.setGet_fromIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // PAYLOAD
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.payload = iprot.readString();
              struct.setPayloadIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // TS
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.ts = iprot.readI64();
              struct.setTsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // EXT_SRV
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list16 = iprot.readListBegin();
                struct.ext_srv = new java.util.ArrayList<java.lang.Integer>(_list16.size);
                int _elem17;
                for (int _i18 = 0; _i18 < _list16.size; ++_i18)
                {
                  _elem17 = iprot.readI32();
                  struct.ext_srv.add(_elem17);
                }
                iprot.readListEnd();
              }
              struct.setExt_srvIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // VALS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list19 = iprot.readListBegin();
                struct.vals = new java.util.ArrayList<KeyValue>(_list19.size);
                KeyValue _elem20;
                for (int _i21 = 0; _i21 < _list19.size; ++_i21)
                {
                  _elem20 = new KeyValue();
                  _elem20.read(iprot);
                  struct.vals.add(_elem20);
                }
                iprot.readListEnd();
              }
              struct.setValsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // KEYS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list22 = iprot.readListBegin();
                struct.keys = new java.util.ArrayList<java.nio.ByteBuffer>(_list22.size);
                java.nio.ByteBuffer _elem23;
                for (int _i24 = 0; _i24 < _list22.size; ++_i24)
                {
                  _elem23 = iprot.readBinary();
                  struct.keys.add(_elem23);
                }
                iprot.readListEnd();
              }
              struct.setKeysIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // SUB_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.sub_type = iprot.readI32();
              struct.setSub_typeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // LOCAL_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.local_id = iprot.readI32();
              struct.setLocal_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // EPOCH
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list25 = iprot.readListBegin();
                struct.epoch = new java.util.ArrayList<EpochEntity>(_list25.size);
                EpochEntity _elem26;
                for (int _i27 = 0; _i27 < _list25.size; ++_i27)
                {
                  _elem26 = new EpochEntity();
                  _elem26.read(iprot);
                  struct.epoch.add(_elem26);
                }
                iprot.readListEnd();
              }
              struct.setEpochIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetTravelId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'travelId' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetStepId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'stepId' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TravelCommand struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.type != null) {
        oprot.writeFieldBegin(TYPE_FIELD_DESC);
        oprot.writeI32(struct.type.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TRAVEL_ID_FIELD_DESC);
      oprot.writeI64(struct.travelId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(STEP_ID_FIELD_DESC);
      oprot.writeI32(struct.stepId);
      oprot.writeFieldEnd();
      if (struct.isSetReply_to()) {
        oprot.writeFieldBegin(REPLY_TO_FIELD_DESC);
        oprot.writeI32(struct.reply_to);
        oprot.writeFieldEnd();
      }
      if (struct.isSetGet_from()) {
        oprot.writeFieldBegin(GET_FROM_FIELD_DESC);
        oprot.writeI32(struct.get_from);
        oprot.writeFieldEnd();
      }
      if (struct.payload != null) {
        if (struct.isSetPayload()) {
          oprot.writeFieldBegin(PAYLOAD_FIELD_DESC);
          oprot.writeString(struct.payload);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetTs()) {
        oprot.writeFieldBegin(TS_FIELD_DESC);
        oprot.writeI64(struct.ts);
        oprot.writeFieldEnd();
      }
      if (struct.ext_srv != null) {
        if (struct.isSetExt_srv()) {
          oprot.writeFieldBegin(EXT_SRV_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, struct.ext_srv.size()));
            for (int _iter28 : struct.ext_srv)
            {
              oprot.writeI32(_iter28);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.vals != null) {
        if (struct.isSetVals()) {
          oprot.writeFieldBegin(VALS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.vals.size()));
            for (KeyValue _iter29 : struct.vals)
            {
              _iter29.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.keys != null) {
        if (struct.isSetKeys()) {
          oprot.writeFieldBegin(KEYS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.keys.size()));
            for (java.nio.ByteBuffer _iter30 : struct.keys)
            {
              oprot.writeBinary(_iter30);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetSub_type()) {
        oprot.writeFieldBegin(SUB_TYPE_FIELD_DESC);
        oprot.writeI32(struct.sub_type);
        oprot.writeFieldEnd();
      }
      if (struct.isSetLocal_id()) {
        oprot.writeFieldBegin(LOCAL_ID_FIELD_DESC);
        oprot.writeI32(struct.local_id);
        oprot.writeFieldEnd();
      }
      if (struct.epoch != null) {
        if (struct.isSetEpoch()) {
          oprot.writeFieldBegin(EPOCH_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.epoch.size()));
            for (EpochEntity _iter31 : struct.epoch)
            {
              _iter31.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TravelCommandTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TravelCommandTupleScheme getScheme() {
      return new TravelCommandTupleScheme();
    }
  }

  private static class TravelCommandTupleScheme extends org.apache.thrift.scheme.TupleScheme<TravelCommand> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TravelCommand struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI32(struct.type.getValue());
      oprot.writeI64(struct.travelId);
      oprot.writeI32(struct.stepId);
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetReply_to()) {
        optionals.set(0);
      }
      if (struct.isSetGet_from()) {
        optionals.set(1);
      }
      if (struct.isSetPayload()) {
        optionals.set(2);
      }
      if (struct.isSetTs()) {
        optionals.set(3);
      }
      if (struct.isSetExt_srv()) {
        optionals.set(4);
      }
      if (struct.isSetVals()) {
        optionals.set(5);
      }
      if (struct.isSetKeys()) {
        optionals.set(6);
      }
      if (struct.isSetSub_type()) {
        optionals.set(7);
      }
      if (struct.isSetLocal_id()) {
        optionals.set(8);
      }
      if (struct.isSetEpoch()) {
        optionals.set(9);
      }
      oprot.writeBitSet(optionals, 10);
      if (struct.isSetReply_to()) {
        oprot.writeI32(struct.reply_to);
      }
      if (struct.isSetGet_from()) {
        oprot.writeI32(struct.get_from);
      }
      if (struct.isSetPayload()) {
        oprot.writeString(struct.payload);
      }
      if (struct.isSetTs()) {
        oprot.writeI64(struct.ts);
      }
      if (struct.isSetExt_srv()) {
        {
          oprot.writeI32(struct.ext_srv.size());
          for (int _iter32 : struct.ext_srv)
          {
            oprot.writeI32(_iter32);
          }
        }
      }
      if (struct.isSetVals()) {
        {
          oprot.writeI32(struct.vals.size());
          for (KeyValue _iter33 : struct.vals)
          {
            _iter33.write(oprot);
          }
        }
      }
      if (struct.isSetKeys()) {
        {
          oprot.writeI32(struct.keys.size());
          for (java.nio.ByteBuffer _iter34 : struct.keys)
          {
            oprot.writeBinary(_iter34);
          }
        }
      }
      if (struct.isSetSub_type()) {
        oprot.writeI32(struct.sub_type);
      }
      if (struct.isSetLocal_id()) {
        oprot.writeI32(struct.local_id);
      }
      if (struct.isSetEpoch()) {
        {
          oprot.writeI32(struct.epoch.size());
          for (EpochEntity _iter35 : struct.epoch)
          {
            _iter35.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TravelCommand struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.type = edu.dair.sgdb.thrift.TravelCommandType.findByValue(iprot.readI32());
      struct.setTypeIsSet(true);
      struct.travelId = iprot.readI64();
      struct.setTravelIdIsSet(true);
      struct.stepId = iprot.readI32();
      struct.setStepIdIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(10);
      if (incoming.get(0)) {
        struct.reply_to = iprot.readI32();
        struct.setReply_toIsSet(true);
      }
      if (incoming.get(1)) {
        struct.get_from = iprot.readI32();
        struct.setGet_fromIsSet(true);
      }
      if (incoming.get(2)) {
        struct.payload = iprot.readString();
        struct.setPayloadIsSet(true);
      }
      if (incoming.get(3)) {
        struct.ts = iprot.readI64();
        struct.setTsIsSet(true);
      }
      if (incoming.get(4)) {
        {
          org.apache.thrift.protocol.TList _list36 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, iprot.readI32());
          struct.ext_srv = new java.util.ArrayList<java.lang.Integer>(_list36.size);
          int _elem37;
          for (int _i38 = 0; _i38 < _list36.size; ++_i38)
          {
            _elem37 = iprot.readI32();
            struct.ext_srv.add(_elem37);
          }
        }
        struct.setExt_srvIsSet(true);
      }
      if (incoming.get(5)) {
        {
          org.apache.thrift.protocol.TList _list39 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.vals = new java.util.ArrayList<KeyValue>(_list39.size);
          KeyValue _elem40;
          for (int _i41 = 0; _i41 < _list39.size; ++_i41)
          {
            _elem40 = new KeyValue();
            _elem40.read(iprot);
            struct.vals.add(_elem40);
          }
        }
        struct.setValsIsSet(true);
      }
      if (incoming.get(6)) {
        {
          org.apache.thrift.protocol.TList _list42 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.keys = new java.util.ArrayList<java.nio.ByteBuffer>(_list42.size);
          java.nio.ByteBuffer _elem43;
          for (int _i44 = 0; _i44 < _list42.size; ++_i44)
          {
            _elem43 = iprot.readBinary();
            struct.keys.add(_elem43);
          }
        }
        struct.setKeysIsSet(true);
      }
      if (incoming.get(7)) {
        struct.sub_type = iprot.readI32();
        struct.setSub_typeIsSet(true);
      }
      if (incoming.get(8)) {
        struct.local_id = iprot.readI32();
        struct.setLocal_idIsSet(true);
      }
      if (incoming.get(9)) {
        {
          org.apache.thrift.protocol.TList _list45 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.epoch = new java.util.ArrayList<EpochEntity>(_list45.size);
          EpochEntity _elem46;
          for (int _i47 = 0; _i47 < _list45.size; ++_i47)
          {
            _elem46 = new EpochEntity();
            _elem46.read(iprot);
            struct.epoch.add(_elem46);
          }
        }
        struct.setEpochIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

