/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.dair.sgdb.thrift;


public enum TravelCommandType implements org.apache.thrift.TEnum {
  TRAVEL(1),
  TRAVEL_MASTER(2),
  TRAVEL_RTN(3),
  TRAVEL_REG(4),
  TRAVEL_FIN(5),
  TRAVEL_NEXT(6),
  TRAVEL_EXTEND(7),
  TRAVEL_LAST(8),
  SYNC_TRAVEL(9),
  SYNC_TRAVEL_MASTER(10),
  SYNC_TRAVEL_RTN(11),
  SYNC_TRAVEL_START(12),
  SYNC_TRAVEL_EXTEND(13),
  SYNC_TRAVEL_FINISH(14),
  TRAVEL_DEL(15),
  TRAVEL_SYNC_DEL(16);

  private final int value;

  private TravelCommandType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TravelCommandType findByValue(int value) { 
    switch (value) {
      case 1:
        return TRAVEL;
      case 2:
        return TRAVEL_MASTER;
      case 3:
        return TRAVEL_RTN;
      case 4:
        return TRAVEL_REG;
      case 5:
        return TRAVEL_FIN;
      case 6:
        return TRAVEL_NEXT;
      case 7:
        return TRAVEL_EXTEND;
      case 8:
        return TRAVEL_LAST;
      case 9:
        return SYNC_TRAVEL;
      case 10:
        return SYNC_TRAVEL_MASTER;
      case 11:
        return SYNC_TRAVEL_RTN;
      case 12:
        return SYNC_TRAVEL_START;
      case 13:
        return SYNC_TRAVEL_EXTEND;
      case 14:
        return SYNC_TRAVEL_FINISH;
      case 15:
        return TRAVEL_DEL;
      case 16:
        return TRAVEL_SYNC_DEL;
      default:
        return null;
    }
  }
}
